"use strict";
let estaChovendo = false;
let idade = 27;
let altura = 1.75;
const nacionalidade = 'parma';
const colegas = ['lucas', 'fernamda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['gian', true, 27];
let idadeDaAna = 25;
let dadosDaApi;
